#define SERVER_ADDR "18.142.250.190"

#define SIZE 1024
#define BUFF_SIZE 4096
#define MIN_SIZE 255
#define MAX_QUERY_LEN 255
#define MAX_MEMBER_COUNT 10

#define COLOR_RED "\x1b[31m"
#define COLOR_GREEN "\x1b[32m"
#define COLOR_BLUE "\x1b[34m"
#define COLOR_RESET "\x1b[0m"

#define db_host "localhost"
#define db_user "network"
#define db_pass "password"
#define db_name "network"

#define FN_SIGN_IN 0
#define FN_SIGN_UP 1
#define FN_PROFILE 2
#define FN_MY_SPACE 3
#define FN_ACCESS_SPACE 4
#define FN_CREATE_SPACE 5
#define FN_SHARE_SPACE 6
#define FN_LIST_MEMBER 7
#define FN_ADD_MEMBER 8
#define FN_DELETE_MEMBER 9
#define FN_DELETE_SPACE 10
#define FN_CREATE_DIR 11
#define FN_REMOVE_DIR 12
#define FN_UPLOAD_FILE 13
#define FN_DOWNLOAD_FILE 14
#define FN_REMOVE_FILE 15
#define FN_OUT_SPACE 16
#define FN_ACCESS_SHARE_SPACE 17
#define FN_LIST_FOLDER 18
#define FN_LIST_FILE 19
#define FN_LIST_ALL_USER 20

#define SIGN_IN "0"
#define SIGN_UP "1"
#define PROFILE "2"
#define MY_SPACE "3"
#define ACCESS_SPACE "4"
#define CREATE_SPACE "5"
#define LIST_MEMBER "7"
#define SHARE_SPACE "6"
#define ADD_MEMBER "8"
#define DELETE_MEMBER "9"
#define DELETE_SPACE "10"
#define CREATE_DIR "11"
#define REMOVE_DIR "12"
#define UPLOAD_FILE "13"
#define DOWNLOAD_FILE "14"
#define REMOVE_FILE "15"
#define OUT_SPACE "16"
#define ACCESS_SHARE_SPACE "17"
#define LIST_FOLDER "18"
#define LIST_FILE "19"
#define LIST_ALL_USER "20"
